language: python
python: 3.4
script:
    - python loadtest.py
install:
    - pip install requests
notifications:
    email: tarek@mozilla.com
    irc: "irc.freenode.org#mozilla-circus"
    on_success: change
